# 配置 Mysql 需要修改的常量
MYSQL_HOST: 139.155.90.176:3306
MYSQL_USERNAME: ENC(wv7ZajBE7Fida2xzgYhBmTT2BPzuQC+Kq1Vd2ZC7NjZJXBUZmk4mFdKSnPwzvkyE)
MYSQL_PASSWORD: ENC(wv7ZajBE7Fida2xzgYhBmTT2BPzuQC+Kq1Vd2ZC7NjZJXBUZmk4mFdKSnPwzvkyE)

# 配置 Druid 的用户名和密码
DRUID_USERNAME: yuejianli
DRUID_PASSWORD: ENC(1gDhO2RSRp5O4Y7E/lC0rfnX3U6MaZO/dvvmVCMAi8XgINr6KlWqM9pDTSo5yfGu)

# 配置Redis 的信息:
REDIS_HOST: 139.155.90.176
REDIS_PORT: 6379
REDIS_PASSWORD: zk123
REDIS_DATABASE: 8

# 配置 swagger 的用户名和密码
SWAGGER_USERNAME: admin
SWAGGER_PASSWORD: ENC(oNEYdaPhQJloQiYdM2lecPtjcIVgJW6Jj08nzIYy6IpMtvM0v6mgqOdJ3XQDlCuX)

# 是否开启xxl_job的相应时间验证
xxlJobTime: true

server:
  port: 8088
  servlet:
    context-path: /StockApi
  #设置头的大小
  max-http-header-size: 102400
# 指定目录
uploadFilePath: /usr/app
# 引入 数据库的相关配置
spring:
  main:
    allow-bean-definition-overriding: true
  # 配置 json
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/stock?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxActive: 100
    minIdle: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    # filters: stat, wall, log4j   # wall暂不启用，如果启用，需要设置multiStatementAllow为true
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
    druid:
      aop-patterns: top.yueshushu.learn.mapper.*,top.yueshushu.learn.service.impl.*
  # 配置Redis的使用
  redis:
    database: ${REDIS_DATABASE}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    # 超时时间  5000毫秒
    timeout: 5000
    # 连接池 lettuce 的配置
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-wait: 100000
  # 配置发送邮件# 配置发送邮件
  mail:
    host: smtp.qq.com # smtp.qq.com 对应的ip
    username: 2048146495@qq.com
    password: ENC(c07QVoS4Sv9u/zlrwEJaLty37vNkW5Nwc3NGEbomI+mP64xRGS2ly3nRja4Btee/ujd+7w+V/3tpD1CKBydVQQ==)
    port: 465
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  velocity:
    FILE_RESOURCE_LOADER_PATH: src/main/resources/templates
#整合mybatis时使用的。   去掉整合 MyBatis的配置信息
mybatis-plus:
  # 配置 mapper文件的位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 配置日志
  configuration:
    map-underscore-to-camel-case: true #  配置数据库表的列别名设置
    # 关闭mybatis一级缓存，防止事务和缓存同时打开引起的查询异常
    local-cache-scope: STATEMENT
    #查看mybatis的SQL, 线上服务器关闭
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag   # 逻辑删除的字段
      logic-not-delete-value: 1  # 正常状态下，该字段的值
      logic-delete-value: 0      # 删除后，该字段的值
      table-underline: true # 驼峰方式转换
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 配置token生成
jwt:
  key: "saaa-ihrm"
  ttl: "3600000"
# 跳转到某个页面
login:
  noLoginUrl: http://www.yueshushu.top/Stock/login.html
#配置 swagger
swagger:
  show: true
  production: false
  basic:
    enable: true
    username: ${SWAGGER_USERNAME}
    password: ${SWAGGER_PASSWORD}
# 支持上传文件
multipart:
  enabled: true
# 默认的查询接口配置
default:
  # 展示今天的股票信息
  show_day_url: https://hq.sinajs.cn/list={0}
  # 展示所有的股票信息
  all_stock_url: >
    https://20.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=10000000&np=1&fid=f3&fields={0}&fs=m:0+t:6,m:0+t:13,m:0+t:80,m:1+t:2,m:1+t:23,b:MK0021,b:MK0022,b:MK0023,b:MK0024
  # 查询这个股票的历史信息
  stock_history_url: >
    http://push2his.eastmoney.com/api/qt/stock/kline/get?
    fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61
    &klt=101&fqt=1&secid={}&beg={}&end={}
  stock_history_download_url: "http://quotes.money.163.com/service/chddata.html?code={0}&start={1}&end={2}\
  &fields=TCLOSE;HIGH;LOW;TOPEN;LCLOSE;CHG;PCHG;TURNOVER;VOTURNOVER;VATURNOVER;TCAP;MCAP"
  #k线图
  min_url: http://image.sinajs.cn/newchart/min/n/{0}.gif
  daily_url: http://image.sinajs.cn/newchart/daily/n/{0}.gif
  weekly_url: http://image.sinajs.cn/newchart/weekly/n/{0}.gif
  monthly_url: http://image.sinajs.cn/newchart/monthly/n/{0}.gif
  # 东方财富的最近一个交易日的数据
  easy_money_history_url: "https://20.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=10000000&np=1&fid=f3&fields=f2,f3,\
                             f4,f5,f6,f12,f14,f15,f16,f17,f18&fs=m:0+t:6,m:0+t:13,m:0+t:80,m:0+t:81+s:2048,m:1+t:2,\
                             m:1+t:23,b:MK0021,\
                             b:MK0022,b:MK0023,b:MK0024%22"
  tx_money_history_url: http://qt.gtimg.cn?q={0}
# 微信发送的配置信息
weixin:
  corpId: ENC(5NynxYfBMsJQellJS1hVS+g7jCOaCqDOhqIftIDeaf0R1xmLBYsrD0nZPgOYa1r413IaYAtFz1+FCJz0Lah8YA==)
  coprsecret: ENC(VgGGFEP4B8Azohzz69QBTlRLZ/GnXAZrdydxo/M3lzE004LbRBPX0c1Nt9YBHVoPxV5Xgc69+t1Dx9YrTLcnp7era8il0zCzoYaBg1EQyew=)
  agentId: 1000003
# 配置文件加密设置
# 指定bean
jasypt:
  encryptor:
    bean: CodeEncrypBean
# 天行接口使用
tianxing:
  key1: bdea38f89ed9d2f98f626225ffe453f4
  key2: 682b53e4b8e13c01a94200c5815c49e4